spring:
  application:
    name: CloudMarketLogin
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 10.8.154.43:8848
  datasource:
    url: jdbc:mysql://localhost:3306/cloudmarket?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8081

